//
// Device.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Device: Codable {
    public var id: Int64?
    public var userId: Int64?
    public var pushId: String?
    public var platform: String?

    public init(id: Int64? = nil, userId: Int64? = nil, pushId: String? = nil, platform: String? = nil) {
        self.id = id
        self.userId = userId
        self.pushId = pushId
        self.platform = platform
    }

}
