//
// Retweet.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Retweet: Codable { 


    public var id: Int64?
    public var userId: Int64?
    public var tweetId: Int64?

    public init(id: Int64? = nil, userId: Int64? = nil, tweetId: Int64? = nil) {
        self.id = id
        self.userId = userId
        self.tweetId = tweetId
    }

}
