//
// Trend.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Trend: Codable { 


    public var id: Int64?
    public var text: String?

    public init(id: Int64? = nil, text: String? = nil) {
        self.id = id
        self.text = text
    }

}
