//
// UserResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct UserResponse: Codable { 


    public var user: User?

    public init(user: User? = nil) {
        self.user = user
    }

}
