//
// User.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct User: Codable {
    public var id: Int64?
    public var twitterHandle: String?
    public var apiKey: String?
    public var retweetsCount: Int?
    public var hasShared: Bool?
    public var isSupporter: Bool?
    public var pushProviderId: String?
}
