//
// Version.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Version: Codable { 


    public var version: String?

    public init(version: String? = nil) {
        self.version = version
    }

}
