// Configuration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import LUX
import FunNet

public let serverConfiguration = ServerConfiguration(scheme: "https", host: "asknot.herokuapp.com", apiRoute: "/api/v1")

public struct AppEnv {
    public var serverConfig = serverConfiguration
    public var twitterServerConfig = ServerConfiguration(host: "api.twitter.com", apiRoute: "1.1")
}

public var Current = AppEnv()

public extension EndpointProtocol {
    func makeCombineCall(serverConfig: ServerConfiguration = Current.serverConfig, responder: CombineNetworkResponder? = CombineNetworkResponder()) -> CombineNetCall {
        return CombineNetCall(configuration: serverConfig, self, responder: responder)
    }
}

func netCall(from endpoint: Endpoint) -> CombineNetCall {
    return CombineNetCall(configuration: Current.serverConfig, endpoint)
}
