devices([
   "iPhone 8 Plus",
   "iPhone 11 Pro Max",
   "iPad Pro (12.9-inch) (3rd generation)"
])
languages(["en-US"])
scheme("ANLibUITests")
output_directory("./screenshots")
clear_previous_screenshots(true)
